puts "The students of my cohort at Makers Academy"
puts "-----------"
puts "Alex Parkinson"
puts "Arfah Farooq"
puts "Carrie Christenson"
puts "Chris Ward"
puts "Cia Walsh"
puts "Costas Sarris"
puts "Diego Romero"
puts "Ed Brown"
puts "Erik Griffin"
puts "Gabe Arafa"
puts "Hannah Carney"
